<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="fb_Test" Id="{fd706bea-6946-439a-af9c-cac1aa70581d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK fb_Test
VAR_INPUT
END_VAR
VAR_OUTPUT
	iCount : int;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[iCount := iCount + 1;]]></ST>
    </Implementation>
    <LineIds Name="fb_Test">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>